stages:
  - lint
  - check
  - test

linter:5.6:
  stage: lint
  image: umutphp/php-docker-images-for-ci:5.6
  script:
    - parallel-lint --exclude vendor .

linter:7.0:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - parallel-lint --exclude vendor .


linter:7.1:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - parallel-lint --exclude vendor .

linter:7.2:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - parallel-lint --exclude vendor .

linter:7.3:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - parallel-lint --exclude vendor .

checker:5.6:
  stage: check
  image: umutphp/php-docker-images-for-ci:5.6
  script:
    - phpcs .

checker:7.0:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - phpcs .

checker:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - phpcs .

checker:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - phpcs .

checker:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - phpcs .
