stages:
  - lint
  - check
  - security
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - vendor/
  - composer.lock

before_script:
  # Run Composer
  - composer install

linter:7.0:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - parallel-lint --exclude vendor .


linter:7.1:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - parallel-lint --exclude vendor .

linter:7.2:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - parallel-lint --exclude vendor .

linter:7.3:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - parallel-lint --exclude vendor .

checker:7.0:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .

checker:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .

checker:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .

checker:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .

composer-checker:
  stage: security
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - security-checker security:check composer.lock

unittest:7.0:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - ls -la
    - ls -la ./vendor
    #- ls -la ./vendor/bin
    - ls -la /usr/local/bin/
    #- ./vendor/bin/phpunit

unittest:7.1:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - ./vendor/bin/phpunit

unittest:7.2:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - ./vendor/bin/phpunit

unittest:7.3:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - ./vendor/bin/phpunit
