stages:
  - lint
  - check
  - security
  - test
  - build

merge_conflict_checker:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - merge_conflict_checker .
  only:
    - master
    - develop
    - /^feature.*$/

gitignore_checker:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.0
  allow_failure: true
  script:
    - gitignore_checker
  only:
    - master
    - develop
    - /^feature.*$/

linter:7.0:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - parallel-lint --exclude vendor .
  only:
    - master
    - develop
    - /^feature.*$/


linter:7.1:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - parallel-lint --exclude vendor .
  only:
    - master
    - develop
    - /^feature.*$/

linter:7.2:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - parallel-lint --exclude vendor .
  only:
    - master
    - develop
    - /^feature.*$/

linter:7.3:
  stage: lint
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - parallel-lint --exclude vendor .
  only:
    - master
    - develop
    - /^feature.*$/

phpcs:7.0:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  only:
    - master
    - develop
    - /^feature.*$/

phpcs:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  only:
    - master
    - develop
    - /^feature.*$/

phpcs:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  only:
    - master
    - develop
    - /^feature.*$/

phpcs:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  only:
    - master
    - develop
    - /^feature.*$/

var-dump-check:7.0:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - var-dump-check .
  only:
    - master
    - develop
    - /^feature.*$/

var-dump-check:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - var-dump-check .
  only:
    - master
    - develop
    - /^feature.*$/

var-dump-check:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - var-dump-check .
  only:
    - master
    - develop
    - /^feature.*$/

var-dump-check:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - var-dump-check .
  only:
    - master
    - develop
    - /^feature.*$/

phpmnd:7.0:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - phpmnd .
  only:
    - master
    - develop
    - /^feature.*$/

phpmnd:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - phpmnd .
  only:
    - master
    - develop
    - /^feature.*$/

phpmnd:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - phpmnd .
  only:
    - master
    - develop
    - /^feature.*$/

phpmnd:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - phpmnd .
  only:
    - master
    - develop
    - /^feature.*$/

phpcpd:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - phpcpd --exclude=vendor .
  only:
    - master
    - develop
    - /^feature.*$/

phpcpd:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - phpcpd --exclude=vendor .
  only:
    - master
    - develop
    - /^feature.*$/

phpcpd:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - phpcpd --exclude=vendor .
  only:
    - master
    - develop
    - /^feature.*$/

phpdcd:7.0:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - phpdcd -vvv --exclude vendor --exclude tests .
  only:
    - master
    - develop
    - /^feature.*$/

phpdcd:7.1:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - phpdcd -vvv --exclude vendor --exclude tests .
  only:
    - master
    - develop
    - /^feature.*$/

phpdcd:7.2:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - phpdcd -vvv --exclude vendor --exclude tests .
  only:
    - master
    - develop
    - /^feature.*$/

phpdcd:7.3:
  stage: check
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - phpdcd -vvv --exclude vendor --exclude tests .
  only:
    - master
    - develop
    - /^feature.*$/

composer-checker:
  stage: security
  image: umutphp/php-docker-images-for-ci:7.1
  before_script:
    - composer install
  script:
    - security-checker security:check composer.lock
  only:
    - master
    - develop
    - /^feature.*$/

psecio-parse:
  stage: security
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - psecio-parse -vvv scan ./src/
  only:
    - master
    - develop
    - /^feature.*$/

unittest:7.0:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.0
  before_script:
    - composer install
  script:
    - ./phpunit
  only:
    - master
    - develop
    - /^feature.*$/

unittest:7.1:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.1
  before_script:
    - composer install
  script:
    - ./phpunit
  only:
    - master
    - develop
    - /^feature.*$/

unittest:7.2:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.2
  before_script:
    - composer install
  script:
    - ./phpunit
  only:
    - master
    - develop
    - /^feature.*$/

unittest:7.3:
  stage: test
  image: umutphp/php-docker-images-for-ci:7.3
  before_script:
    - composer install
  script:
    - ./vendor/phpunit/phpunit/phpunit
  only:
    - master
    - develop
    - /^feature.*$/

buid:5.6:
  stage: build
  image: umutphp/php-docker-images-for-ci:5.6
  script:
    - composer install
  only:
    - master
    - develop
    - /^feature.*$/

buid:7.0:
  stage: build
  image: umutphp/php-docker-images-for-ci:7.0
  script:
    - composer install
  only:
    - master
    - develop
    - /^feature.*$/

build:7.1:
  stage: build
  image: umutphp/php-docker-images-for-ci:7.1
  script:
    - composer install
  only:
    - master
    - develop
    - /^feature.*$/

build:7.2:
  stage: build
  image: umutphp/php-docker-images-for-ci:7.2
  script:
    - composer install
  only:
    - master
    - develop
    - /^feature.*$/

build:7.3:
  stage: build
  image: umutphp/php-docker-images-for-ci:7.3
  script:
    - composer install
  only:
    - master
    - develop
    - /^feature.*$/
